USE ENTREGA_3;

DROP FUNCTION IF EXISTS CANTIDAD_FAVORITOS_USUARIOS;
DELIMITER //
CREATE FUNCTION CANTIDAD_FAVORITOS_USUARIOS (NOMBRE CHAR(30))
RETURNS INT
DETERMINISTIC
BEGIN
DECLARE RESPUESTA INT DEFAULT 0; 
SET RESPUESTA = (SELECT COUNT(*)
FROM FAVORITOS F
JOIN USUARIOS U ON (F.ID_USUARIO = U.ID)
JOIN PRODUCTOS P ON (P.ID = F.ID_PRODUCTO)
WHERE U.NOMBRE = NOMBRE);
RETURN RESPUESTA;
END
//
DELIMITER ;

SELECT CANTIDAD_FAVORITOS_USUARIOS('Alexis');

DROP FUNCTION IF EXISTS TOTAL_CARRITO_COMPRAS;
DELIMITER //
CREATE FUNCTION TOTAL_CARRITO_COMPRAS (NOMBRE CHAR(30))
RETURNS INT
DETERMINISTIC
BEGIN
DECLARE RESPUESTA INT DEFAULT 0; 
SET RESPUESTA = (SELECT SUM(C.PRECIO_TOTAL)
FROM CARRITO_COMPRAS C
JOIN USUARIOS U ON (C.ID_USUARIO = U.ID)
WHERE U.NOMBRE= 'Veronica');
RETURN RESPUESTA;
END
//
DELIMITER ;

SELECT TOTAL_CARRITO_COMPRAS('Veronica');
