USE ENTREGA_3;

CREATE OR REPLACE VIEW favoritos AS
(SELECT U.NOMBRE AS USUARIO_NOMBRE,P.NOMBRE AS PRODUCTO_NOMBRE
FROM FAVORITOS F
JOIN USUARIOS U ON (F.ID_USUARIO=U.ID)
JOIN PRODUCTOS P ON (P.ID=F.ID_PRODUCTO)
);

CREATE OR REPLACE VIEW comics AS
(SELECT NOMBRE, STOCK, DESCRIPCION, PRECIO
FROM PRODUCTOS
WHERE CATEGORIA='Comic');

CREATE OR REPLACE VIEW manga AS
(SELECT NOMBRE, STOCK, DESCRIPCION, PRECIO
FROM PRODUCTOS
WHERE CATEGORIA='Manga');

CREATE OR REPLACE VIEW compras_procesadas AS
(SELECT *
FROM ORDEN_PAGO
WHERE ESTADO_COMPRA='PROCESADO');

CREATE OR REPLACE VIEW productos_800up AS
(SELECT NOMBRE, STOCK, PRECIO
FROM PRODUCTOS
WHERE PRECIO>800);