USE ENTREGA_3;

DROP PROCEDURE IF EXISTS SP_LISTA_ORDENADA ;

DELIMITER //
CREATE PROCEDURE SP_LISTA_ORDENADA(INOUT P_ORDER VARCHAR(20),
									INOUT P_ASC_DESC VARCHAR(20))
BEGIN

SET @T1 = CONCAT('SELECT NOMBRE, STOCK, PRECIO FROM PRODUCTOS ORDER BY', ' ',P_ORDER, ' ',P_ASC_DESC) ;
PREPARE PARAM_STMT FROM @T1 ;
EXECUTE PARAM_STMT ;
DEALLOCATE PREPARE PARAM_STMT ;

END //
DELIMITER ;

SET @P_ORDER = 'PRECIO' ;
SET @P_ASC_DESC = 'ASC' ;

CALL SP_LISTA_ORDENADA(@P_ORDER,@P_ASC_DESC);


DROP PROCEDURE IF EXISTS SP_ELIMINAR_USUARIO ;

DELIMITER //
CREATE PROCEDURE SP_ELIMINAR_USUARIO(IN P_ID_USUARIO INT)
BEGIN

SET  @ELIMINADO = CONCAT('DELETE FROM USUARIOS
							WHERE ID=',P_ID_USUARIO) ;
                            
PREPARE ELIMINADO FROM @ELIMINADO ;
EXECUTE ELIMINADO ;
                            
END //
DELIMITER ;

SET @P_ID_USUARIO = 1 ;

CALL SP_ELIMINAR_USUARIO(@P_ID_USUARIO);

SELECT * FROM USUARIOS ;



-- EL SIGUIENTE SP NO FUNCIONA Y NO ENCUENTRO EL ERROR EN EL SELECT PREGUNTAR EL POR QUE

/*
DROP PROCEDURE IF EXISTS SP_FAVS_USUARIO;
DELIMITER //
CREATE PROCEDURE SP_FAVS_USUARIO(IN P_NOMBRE VARCHAR(25),
									OUT P_NOMBRE_CLIENTE VARCHAR(25),
									OUT P_PRODUCTO_FAVORITO VARCHAR(250),
									OUT P_PRECIO INT)
BEGIN

SELECT U.NOMBRE, P.NOMBRE, P.PRECIO
INTO P_NOMBRE_CLIENTE, P_PRODUCTO_FAVORITO, P_PRECIO
FROM FAVORITOS F
JOIN USUARIOS U ON (F.ID_USUARIO = U.ID)
JOIN PRODUCTOS P ON (P.ID = F.ID_PRODUCTO)
WHERE U.NOMBRE = P_NOMBRE ;

END//
DELIMITER ;

CALL SP_FAVS_USUARIO('Alexis',@P_NOMBRE_CLIENTE,@P_PRODUCTO_FAVORITO,@P_PRECIO);

SELECT U.NOMBRE AS NOMBRE_CLIENTE, P.NOMBRE AS PRODUCTO_FAVORITO, P.PRECIO
FROM FAVORITOS F
JOIN USUARIOS U ON (F.ID_USUARIO = U.ID)
JOIN PRODUCTOS P ON (P.ID = F.ID_PRODUCTO)
WHERE U.NOMBRE = 'Alexis' ;
*/